---
title: "Comparative"
output: html_document
date: "2024-09-24"
---

```{r echo<-FALSE}
suppressMessages(library(dendextend))
suppressMessages(library(rstudioapi))
suppressMessages(library(openxlsx))
suppressMessages(library(dplyr))
suppressMessages(library(pheatmap))
suppressMessages(library(ggplot2))
suppressMessages(library(ggrepel))
suppressMessages(library(gridExtra))
suppressMessages(library(patchwork))
suppressMessages(library(reshape2))
suppressMessages(library(colorRamp2))
suppressMessages(library(biclust))
suppressMessages(library(vegan))
suppressMessages(library(tidyr))
suppressMessages(library(viridis))
```
```{r echo=FALSE, warning=FALSE}
script_dir <- dirname(getActiveDocumentContext()$path)
setwd(script_dir)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = script_dir)
```

# RNA-seq database

```{r echo=FALSE}

#Dataframe output Kraken
df_rna_frac <- read.delim("../results/brackenabundances_normtss.txt", sep="\t")
df_rna_frac <- df_rna_frac[,!grepl("TT81",colnames(df_rna_frac))] 
df_rna_frac <- df_rna_frac[,!grepl("TT60",colnames(df_rna_frac))]
#Dataframe metadata
meta <- read.xlsx("../local/data/Vulvodinia_Samples.xlsx")
```


# DNA metagenome database

```{r echo=FALSE}

#Dataframe output Kraken
df_dna <- read.delim("../local/data/bracken_merged_abbundances_dna.num.txt", sep="\t")
df_dna <- df_dna[!grepl("sapiens",df_dna$name),]
rownames(df_dna) <- df_dna$name
df_dna <- df_dna[,-c(1:3)]

colnames(df_dna) <- paste(meta[match(colnames(df_dna),meta$PatientID),]$SampleType, colnames(df_dna), sep="_")

df_dna_frac<-sweep(df_dna,2,colSums(df_dna),"/")
knitr::kable(head(df_dna_frac[,1:10],n = 10))

```


```{r}
# ##NORMALIZATION NEGATIVE CONTROL
# Define the columns that will be normalized
batch1<-dplyr::select(df_dna_frac, H_TT20, H_TT28, H_TT54, H_TT60, H_TT81,NA_NC)
batch2 <- df_dna_frac[ , !colnames(df_dna_frac) %in% colnames(batch1)][,-grep("NC",colnames(df_dna_frac))]

sample_columns_batch1 <- colnames(batch1)[-grep("NC",colnames(batch1))]
sample_columns_batch2 <- colnames(batch2)[-grep("NEG",colnames(batch2))]
#batch1
# Subtract the negative control from each sample column and set negatives to 0
for (col in sample_columns_batch1) {
  batch1[[col]] <- pmax(batch1[[col]] - batch1[,grep("NA_NC",colnames(batch1))], 0) 
}
#batch2
# Subtract the negative control from each sample column and set negatives to 0
for (col in sample_columns_batch2) {
  batch2[[col]] <- pmax(batch2[[col]] - batch2[,grep("NA_NEG",colnames(batch2))], 0)  
}

final<-merge(batch1,batch2,by=0) %>% tibble::column_to_rownames("Row.names")
final<- final[,-grep("NA",colnames(final))]
df_dna_frac<-final[which(rowSums(final) != 0),]
```


```{r echo=FALSE, warning=FALSE, message=FALSE}

species=c("Lactobacillus iners","Lactobacillus crispatus","Lactobacillus gasseri","Lactobacillus jensenii")

###RNASEQ###

lactorna=as.data.frame(df_rna_frac[rownames(df_rna_frac) %in% species,])
lactorna=rbind(lactorna,Others=1-colSums(lactorna))
lactorna$Species <- rownames(lactorna)
tlactorna<-as.data.frame(t(lactorna))

###DNASEQ###

lactodna=as.data.frame(df_dna_frac[rownames(df_dna_frac) %in% species,])
lactodna=rbind(lactodna,Others=1-colSums(lactodna))
lactodna$Species <- rownames(lactodna)
tlactodna<-as.data.frame(t(lactodna))

common_columns <- intersect(colnames(lactodna), colnames(lactorna))
lactorna[,common_columns]

d=merge(lactodna,lactorna,by = 0, suffixes = c(".dna", ".rna"))
rownames(d)=d$Row.names
d=d[,c(paste0(common_columns,".dna"),paste0(common_columns,".rna"),"Row.names")]
d$Species=rownames(d)
d$Row.names=NULL
d$Species.dna=NULL
d$Species.rna=NULL

df_long1 <- d[,grepl("\\.dna|Species",colnames(d))] %>%
  pivot_longer(cols = ends_with(".dna"),
               names_to = "sample",
               values_to = "value") 
  

df_long2 <- d[,grepl("\\.rna|Species",colnames(d))] %>%
  pivot_longer(cols = ends_with(".rna"),
               names_to = "sample",
               values_to = "value") 

custom_colors <- c(
  "Lactobacillus iners" = "#92C73E",  # Soft Blue
  "Lactobacillus crispatus" = "#F58B1F",  # Light Orange
  "Lactobacillus jensenii" = "#35459B",  # Soft Green
  "Lactobacillus gasseri" = "#EC1E24",  # Light Red
  "Others" = "#468B74"  # Soft Purple
)

ggplot(rbind(df_long1,df_long2), aes(y = value, x = sample, fill = Species)) +
  geom_col(color="black") +
  scale_fill_manual(values = custom_colors) + 
    theme_minimal() 

a=merge(df_rna_frac,df_dna_frac,by = 0,suffixes = c(".rna",".dna"),all = T)
rownames(a)=a$Row.names
b=a[,grep(".dna|.rna",colnames(a))]
b[is.na(b)]=0



# dist(t(b))
# beta_rna <- vegdist(t(b), method = "jaccard")
beta_rna <- vegdist(t(b), method = "bray")
# beta_rna <- dist(t(b))
betamtx<-as.matrix(beta_rna)

pheatmap(betamtx, 
         # color = viridis,
         clustering_distance_rows = beta_rna,
         clustering_distance_cols = beta_rna)
# beta_rna <- vegdist(t(b[,grep("dna",colnames(b))]), method = "bray")
# beta_dna <- vegdist(t(b[,grep(".rna",colnames(b))]), method = "bray")
# adonis2(beta_rna ~ c(rep("rna",3),rep("dna",3)), method = "bray", permutations = 1000)

hc <- hclust(beta_rna)
clusters <- cutree(hc, k = 6)
### Dendrogramma ###
dend <- as.dendrogram(hc)
# colored_dend <- color_branches(dend, k = 6)
plot(dend, ylab = "Height")





  NMDS <- metaMDS(t(b), distance = "bray", trymax = 100, autotransform = T, k = 4)
score <- as.data.frame(scores(NMDS)$site)
score$sampleID <- rownames(score)
score$trt <- factor(c(rep("rna",nrow(score)/2),rep("dna",nrow(score)/2)),levels=c("rna","dna"))

micro <- as.data.frame(scores(NMDS)$species)
micro$taxa <- b$taxonomy
micro$abund <- colSums(t(b))


score$Samples=sapply(strsplit(score$sampleID,"\\."),"[",1)


ggplot() +
  geom_point(data = score, aes(x = NMDS1, y = NMDS2, shape = trt, fill = trt), 
             size = 7, stroke = 0.5, color = "black", alpha = 0.9) +  # Black outline and transparency
  scale_fill_manual(values = c("#66c2a5", "#fc8d62")) +  # Softer color palette for the fill
  scale_shape_manual(values = c(21, 24)) +  # Hollow circle and triangle for better outline control
  labs(title = "NMDS Plot of Treatment Groups",
       x = "NMDS1", 
       y = "NMDS2",
       fill = "Treatment", 
       shape = "Treatment") + 
  geom_text_repel(data=score,aes(x=NMDS1,y=NMDS2,label = Samples)) +#+ Add labels
  theme_minimal(base_size = 14) +  # Clean theme
  theme(legend.position = "right", 
        panel.grid = element_blank(), 
        plot.title = element_text(hjust = 0.5))  # Center the title





```

```{r}

# Load necessary libraries
library(vegan)     # For distance calculations
library(ape)       # For PCoA
library(plotly)    # For 3D plotting

# Example data: Assuming 'b' is your data, where rows are samples and columns are features
# Transpose the data for PCoA (samples should be rows)
b<-b[,-grep("H_TT23",colnames(b))]
b<-b[,-grep("H_TT28",colnames(b))]
b<-b[,-grep("H_TT55",colnames(b))]
b_transposed <- t(b)


# Step 1: Calculate the Jaccard distance matrix
jaccard_dist <- vegdist(b_transposed, method = "bray")  # Jaccard distance calculation

# Step 2: Perform PCoA
pcoa_result <- pcoa(jaccard_dist, correction = "cailliez")  # PCoA with correction for negative eigenvalues

# Step 3: Extract the coordinates (scores) from the PCoA result
score <- data.frame(pcoa_result$vectors[, 1:3])  # Extract first 3 PCoA axes
score$Samples <- rownames(b_transposed)          # Sample names
score$trt <- factor(c(rep("rna",nrow(score)/2),rep("dna",nrow(score)/2)),levels=c("rna","dna"))

ggplot() +
  geom_point(data = score, aes(x = Axis.1, y = Axis.2, shape = trt, fill = trt), 
             size = 15, stroke = 0.5, color = "black", alpha = 0.9) +  # Black outline and transparency
  scale_fill_manual(values = c("#66c2a5", "#fc8d62")) +  # Softer color palette for the fill
  scale_shape_manual(values = c(21, 24)) +  # Hollow circle and triangle for better outline control
  labs(title = "PCoA Plot of Treatment Groups",
       x = "PCoA1", 
       y = "PCoA2",
       fill = "MetaType", 
       shape = "MetaType") + 
  geom_text_repel(data=score,aes(x=Axis.1,y=Axis.2,label = Samples),max.overlaps = 100) + #+ Add labels
  theme_minimal(base_size = 14)+  # Clean theme
theme(legend.position = "right",
      panel.grid = element_blank(),
      plot.title = element_text(hjust = 0.5)) +
  coord_cartesian(xlim = c(-0.3, 0.25), ylim = c(-0.25, 0.2)) # Set axis limits

```

```{r}
df_counts <- read.table("../results/decontaminated_counts.txt",sep = "\t")
df_counts<-df_counts[,!grepl("TT81",colnames(df_counts))]
df_counts<-df_counts[,!grepl("TT60",colnames(df_counts))]

df_counts = df_counts[, grepl("H_", colnames(df_counts))]
common_columns <- intersect(colnames(df_dna), colnames(df_counts))
merged=merge(df_dna[,common_columns],df_counts[,common_columns],by = 0, suffixes = c(".dna", ".rna"))
rownames(merged)=merged$Row.names
merged$Row.names=NULL
colSums(merged)
prc<-0.1
bac<-merged[-grep("Lactobacillus crispatus|Lactobacillus iners|Lactobacillus jensenii",rownames(merged)),]
merged_filt<-bac

nreads_min<-min(colSums(merged_filt))
nreads_max<-max(colSums(merged_filt))
fold<-round(nreads_max/nreads_min,0)

kdata_subs<-rrarefy(t(merged_filt),nreads_min)
alpha_subs<-diversity(kdata_subs)#t(kdata[,match(ordered_samples,colnames(kdata))])
alphasubs=data.frame(samples=names(alpha_subs),value=alpha_subs)
alphasubs$samples<-factor(alphasubs$samples)


ggplot(alphasubs, aes(x = samples, y = factor(1), size = value, colour = value)) +
  geom_point() +
  scale_size_continuous(range = c(5, 15)) +
  scale_color_gradient(low = "grey90", high = "#D94943") +  # Intensity of color
  theme_bw() +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none"  # Hide the legend
  )+
  coord_fixed(ratio = 2)
```
```{r}
common_columns <- intersect(colnames(df_rna_frac), colnames(df_dna_frac))
df_rna_frac[,common_columns]
merged=merge(df_dna_frac[,common_columns],df_rna_frac[,common_columns],by = 0, suffixes = c(".dna", ".rna"))
rownames(merged)=merged$Row.names
merged$Row.names=NULL
colSums(merged)
prc<-0.1
bac<-rowSums(apply(merged,2,FUN = function(x) x>=prc))>=1
```

```{r}
merged_all = merge(df_dna_frac[,common_columns], df_rna_frac[,common_columns], by = 0, suffixes = c(".dna", ".rna"), all = TRUE)
merged_all[is.na(merged_all)] <- 0
merged_all<-tibble::column_to_rownames(merged_all,"Row.names")
genus_frac<-merged_all
genus_frac$genus<-sapply(strsplit(rownames(genus_frac)," "),"[",1) 
genus_frac<-genus_frac %>%
  group_by(genus) %>%
  summarise(across(everything(), sum, na.rm = TRUE)
  )%>% tibble::column_to_rownames("genus")

genus_frac$sum <- rowSums(genus_frac)

genus_frac<-arrange(genus_frac,desc(sum))
genus_frac$sum<-NULL
genus_frac<-sweep(genus_frac,2,colSums(genus_frac),"/")

colSums(genus_frac)
# Calcola la varianza per ogni riga
row_var <- apply(genus_frac, 1, var)

# Mantieni solo le righe con varianza diversa da 0
genus_frac <- genus_frac[row_var != 0, ]
prc=0.05
#--- Show only the ones over 20%
bac<-rowSums(apply(genus_frac,2,FUN = function(x) x>= prc))>=1
genus_frac_filt<-genus_frac[bac,]
genus_frac_filt<-binarize(genus_frac_filt,threshold =0)

pheatmap(genus_frac_filt)
pheatmap(genus_frac,scale = "row",
          breaks= seq(-1.5,1.5,length.out=100))

```
```{r}

genus_frac<-merged_all
genus_frac$genus<-sapply(strsplit(rownames(genus_frac)," "),"[",1) 
genus_frac<-genus_frac %>%
  group_by(genus) %>%
  summarise(across(everything(), sum, na.rm = TRUE)
  )%>% tibble::column_to_rownames("genus")

genus_frac$sum <- rowSums(genus_frac)

genus_frac<-arrange(genus_frac,desc(sum))
genus_frac$sum<-NULL
genus_frac<-sweep(genus_frac,2,colSums(genus_frac),"/")
# Define the thresholds for 10% and 1% abundance
prc_10 <- 0.1
prc_01 <- 0.05
# Calculate rows meeting the 10% abundance condition
bac_10 <- rowSums(apply(genus_frac, 2, FUN = function(x) x >= prc_10)) >= 1
genus_frac <- genus_frac[!bac_10,]
# Calculate rows meeting the 1% abundance condition
bac_01 <- rowSums(apply(genus_frac, 2, FUN = function(x) x >= prc_01)) >= 1
genus_frac <- genus_frac[bac_01,]
# Select rows that meet either the 10% or 1% abundance condition
row_var <- apply(genus_frac, 1, var)
genus_frac <- genus_frac[row_var != 0, ]
pheatmap(genus_frac,scale = "row",   breaks= seq(-1.5,1.5,length.out=100))
```

```{r}
prc<-0.1
bac<-rowSums(apply(merged,2,FUN = function(x) x>=prc))>=1
merged_filt<-merged[bac,]
merged_filt[paste0("Less than ",prc*100,"%"),]<-1-colSums(merged_filt)
merged_filt$Species <- rownames(merged_filt)
# merged_filt$Species <- factor(merged_filt$Species ,levels = c("Gardnerella swidsinskii", "Gardnerella vaginalis", "Lactobacillus crispatus", "Lactobacillus iners"  ,"Lactobacillus jensenii","Prevotella bivia", "Less than 5%"))
#### Plot Abbondanze ####
data_long_gen <- merged_filt %>%
  pivot_longer(
    cols = starts_with("H_"),   # Specify the columns to pivot
    names_to = "Category",       # Name of the new column for the original column names
    values_to = "Value"          # Name of the new column for the values
  ) 

library(forcats)

# Assicurati che "Others" sia l'ultimo livello del fattore Species
    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c(paste0("Less than ",prc*100,"%")), after = Inf)
        data_long_gen$Species <- fct_relevel(data_long_gen$Species, c( "Gardnerella swidsinskii"), after = 3)
    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c("Gardnerella vaginalis"), after = 4)
    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c("Prevotella bivia"), after = 5)

    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c("Lactobacillus crispatus"), after = 0)
    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c("Lactobacillus iners"), after = 1)
    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c("Lactobacillus jensenii"), after = 2)

ggplot(data_long_gen, aes(y = Value, x = Category, fill = Species,)) +
  geom_col(color="black") +
 scale_fill_manual(values =c("#F58B1F", "#92C73E", "#35459B" ,"#bf63a3", "#e8a2c0","#ffd761","#468B74","grey"))+# Aggiungi le etichette sopra le barre
  theme_minimal()  # Usa un tema semplice


```

```{r}
genus_frac<-merged
genus_frac$genus<-sapply(strsplit(rownames(genus_frac)," "),"[",1) 
genus_frac<-genus_frac %>%
  group_by(genus) %>%
  summarise(across(everything(), sum, na.rm = TRUE)
  )%>% tibble::column_to_rownames("genus")

genus_frac$sum <- rowSums(genus_frac)
genus_frac<-arrange(genus_frac,desc(sum))
genus_frac$sum<-NULL
genus_frac$Species<-NULL

prc<-0.03
bac<-rowSums(apply(genus_frac,2,FUN = function(x) x>=prc))>=1
genus_frac_filt<-genus_frac[bac,]
genus_frac_filt[paste0("Less than ",prc*100,"%"),]<-1-colSums(genus_frac_filt)
genus_frac_filt$Species <- rownames(genus_frac_filt)
# merged_filt$Species <- factor(merged_filt$Species ,levels = c("Gardnerella swidsinskii", "Gardnerella vaginalis", "Lactobacillus crispatus", "Lactobacillus iners"  ,"Lactobacillus jensenii","Prevotella bivia", "Less than 5%"))
#### Plot Abbondanze ####
data_long_gen <- genus_frac_filt %>%
  pivot_longer(
    cols = starts_with("H_"),   # Specify the columns to pivot
    names_to = "Category",       # Name of the new column for the original column names
    values_to = "Value"          # Name of the new column for the values
  ) 


library(forcats)

# Assicurati che "Others" sia l'ultimo livello del fattore Species
    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c(paste0("Less than ",prc*100,"%")), after = Inf)
        data_long_gen$Species <- fct_relevel(data_long_gen$Species, c( "Gardnerella swidsinskii"), after = 3)
    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c("Gardnerella vaginalis"), after = 4)
    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c("Prevotella bivia"), after = 5)

    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c("Lactobacillus crispatus"), after = 0)
    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c("Lactobacillus iners"), after = 1)
    data_long_gen$Species <- fct_relevel(data_long_gen$Species, c("Lactobacillus jensenii"), after = 2)

ggplot(data_long_gen, aes(y = Value, x = Category, fill = Species,)) +
  geom_col(color="black") +
 scale_fill_manual(values =c("#F58B1F", "#92C73E", "#35459B" ,"#bf63a3", "#e8a2c0","#ffd761","#468B74","grey"))+
  theme_minimal()
```
```{r}
library(infotheo)
#INFORMATION GAIN
z=data.frame()
for (col in gsub("\\.(dna|rna)","",colnames(b))){
  x<-b[,grep(pattern = col,colnames(b))]

# Discretize metagenome and metatranscriptome abundances into 3 bins (low, medium, high)
  x$Metagenome_discretized <- discretize(x[,2], disc = "equalfreq", nbins = 3)
  x$Metatranscriptome_discretized <- discretize(x[,1], disc = "equalfreq", nbins = 3)

  # Calculate entropy of metatranscriptome
  H_metatranscriptome <- entropy(x$Metatranscriptome_discretized)

  # Calculate conditional entropy of metatranscriptome given metagenome
  H_metatranscriptome_given_metagenome <- condentropy(x$Metatranscriptome_discretized, x$Metagenome_discretized)

  # Calculate Information Gain
  IG <- H_metatranscriptome - H_metatranscriptome_given_metagenome

  y<- data.frame(
    H_metatranscriptome = H_metatranscriptome,
    H_metatranscriptome_given_metagenome = H_metatranscriptome_given_metagenome,
    IG = IG
  )  
  
  z=rbind(z,y)
}

# Output the results
cat("Entropy of Metatranscriptome:", mean(z$H_metatranscriptome), "\n")
cat("Conditional Entropy of Metatranscriptome given Metagenome:", mean(z$H_metatranscriptome_given_metagenome), "\n")
cat("Information Gain:", mean(z$IG), "\n")


```

```{r}
df <- data.frame()

  for (microbe in rownames(merged_all)) {
  rna <- merged_all[microbe,grep(".rna",colnames(merged_all))]+0.00001
  dna <- merged_all[microbe,grep(".dna",colnames(merged_all))]+0.00001
  df <- rbind(df,log(rna/dna))
  }

df
```