---
title: "PaperMicroUltimate"
output: html_document
date: "2024-10-04"
---
```{r echo=FALSE, warning=FALSE}
suppressMessages(library(DirichletMultinomial))
suppressMessages(library(rstudioapi))
suppressMessages(library(openxlsx))
suppressMessages(library(dplyr))
suppressMessages(library(pheatmap))
suppressMessages(library(ggplot2))
suppressMessages(library(ggrepel))
suppressMessages(library(gridExtra))
suppressMessages(library(patchwork))
suppressMessages(library(reshape2))
suppressMessages(library(colorRamp2))
suppressMessages(library(viridis))
suppressMessages(library(edgeR))
suppressMessages(library(readr))
suppressMessages(library(vegan))
suppressMessages(library(dendextend))
suppressMessages(library(tidyr))
suppressMessages(library(ggExtra))
suppressMessages(library(ggpubr))
suppressMessages(library(phyloseq))
suppressMessages(library(decontam))
suppressMessages(library(waffle))
suppressMessages(library(janitor))
suppressMessages(library(rlang))
suppressMessages(library(svglite)) 
```

```{r echo=FALSE, warning=FALSE}
script_dir <- dirname(getActiveDocumentContext()$path)
setwd(script_dir)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = script_dir)
```

### Normalization TSS
```{r}
kdata_filt <- read.delim("../results/counts_decont_filtered.txt", sep="\t")
#------------------------------#
# 1. Total Sum Scaling (TSS) ----
#------------------------------#
kdata_frac<-sweep(kdata_filt,2,colSums(kdata_filt),"/")

```


## PCA on the TSS abundances
```{r echo=FALSE}

#Performing a PCA on these data
data_PCA <- prcomp(t(kdata_frac), scale = T)
scores <- data.frame(sample = rownames(data_PCA$x), PC1 = data_PCA$x[,1], PC2 = data_PCA$x[,2], PC3 = data_PCA$x[,3])
scores$sample <- rownames(scores)
scores$status <- sapply(strsplit(scores$sample,"_"),"[", 1)
scores$PatientID <- sapply(strsplit(scores$sample,"_"),"[", 2)

## **PCA Plot on PC1 vs PC2**
var_explained <- (data_PCA$sdev^2) / sum(data_PCA$sdev^2)
pca_plot <- ggplot(scores, aes(x = PC1, y = PC2 )) +
  geom_point(size = 3, alpha = 1,color="#7EB77F") +  
  theme_minimal(base_size = 14) +     
    
  ggrepel::geom_text_repel(
    aes(label = sample),
    color = "#2D5C2F",      
    size = 2,
    box.padding = 0.35,     
    point.padding = 0.3,
    max.overlaps = 20,      
    segment.color = "gray60",
    min.segment.length = 0.2
  ) +
  labs(
    title = "PCA Plot of Samples",
    x = paste0("PC1 (", round(var_explained[1] * 100, 2), "% Variance)"),
    y = paste0("PC2 (", round(var_explained[2] * 100, 2), "% Variance)"),
    color = "Status",
    shape = "Patient ID"
  ) +
  theme_minimal()+
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16), # Centered title
    axis.text = element_text(size = 12),
    axis.title = element_text(face = "bold"),
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 10)
  )
pca_plot
```

## NMDS on TSS data
```{r echo=FALSE, message=FALSE, warning=FALSE}

NMDS <- vegan::metaMDS(
  t(kdata_frac), 
  distance = "bray", 
  trymax = 100,
  autotransform = TRUE, 
  k = 4                 
)



stress_value <- paste("Stress:", round(NMDS$stress, 3))  
score <- data.frame(
  vegan::scores(NMDS)$site,
  sampleID = rownames(vegan::scores(NMDS)$site)
) %>%
  mutate(
    SampleGroup = sapply(strsplit(sampleID, "\\."), "[", 1)  
  )

ggplot(score, aes(x = NMDS1, y = NMDS2)) +
  geom_point(
    size = 3,
    alpha = 0.9,
    color = "#7EB77F",     
    fill = "#7EB77F30",    
    shape = 21,             
    stroke = 0.7            
  ) +
  ggrepel::geom_text_repel(
    aes(label = SampleGroup),
    color = "#2D5C2F",
    size = 2,
    box.padding = 0.4,
    point.padding = 0.3,
    max.overlaps = 15,
    segment.color = "grey40",
    min.segment.length = 0.15,
    seed = 123              # For reproducible label positions
  ) +
  labs(
    title = "Non-Metric Multidimensional Scaling (NMDS)",
    subtitle = stress_value,
    x = "NMDS Axis 1",
    y = "NMDS Axis 2"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 18),
    plot.subtitle = element_text(hjust = 0.5, color = "gray40"),
    axis.title = element_text(face = "bold", color = "gray30"),
    panel.grid.major = element_line(color = "grey90"),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "white", color = NA)
  ) +
  coord_fixed()  # Maintain aspect ratio

```


# Clustering 

```{r echo=FALSE}
### Matrice di Distanze ###

beta_rna <- vegdist(t(kdata_frac), method = "bray")
betamtx<-as.matrix(beta_rna)
p <- pheatmap(betamtx, 
         # color = viridis,
         clustering_distance_rows = beta_rna,
         clustering_distance_cols = beta_rna)

ggsave(filename = paste0("../results/images/MainRNA/supp/DistanceMatrix.svg"), plot = p, width = 15, height = 6, device = svglite)

###HIERARCHICAL CLUSTERING UNSCALED###
library(phylogram)

hc <- hclust(dist(t(kdata_frac),method = "euclidean"), method = "ward.D2")
clusters <- cutree(hc, k = 4)
### Dendrogramma ###
dend <- as.dendrogram(hc)

colored_dend <- color_branches(dend, k = 4, col = c("#F58B1F", "#92C73E","#EC1E24", "#468B74"  , "#35459B"))
plot(colored_dend, type = "triangle", ylab = "Height")
write.dendrogram(dend, file = "../results/Dendrogram.nwk", edges = TRUE)


#Labels for later orders
ordered_samples <- labels(dend)
ordereds_samples_2 <- sapply(strsplit(ordered_samples,"_"),"[",2)
kdata_frac <- kdata_frac[rowSums(kdata_frac)!=0,match(ordered_samples,colnames(kdata_frac))]


### Setting Dominance of CST found in Vaginal microbiome
species <- c("Lactobacillus iners","Lactobacillus crispatus","Lactobacillus gasseri","Lactobacillus jensenii")
custom_colors <- c(
   "Lactobacillus crispatus" = "#F58B1F",
  "Lactobacillus iners" = "#92C73E",  
  "Lactobacillus gasseri" = "#EC1E24",
  "Others" = "#468B74",  
  "Lactobacillus jensenii" = "#35459B"
  )

### Creating Dominance Dataframe
lacto <- as.data.frame(kdata_frac[rownames(kdata_frac) %in% species,])
cstdata <- rbind(lacto,Others=1-colSums(lacto))
cstdata$Species <- rownames(cstdata)

data_long <- cstdata %>%
  pivot_longer(
    cols = starts_with("H_"),   # Specify the columns to pivot
    names_to = "Category",       # Name of the new column for the original column names
    values_to = "Value"          # Name of the new column for the values
  ) 
data_long$Category<-factor(data_long$Category,levels = ordered_samples)


#### Plot Abbondanze ####

p <- ggplot(data_long, aes(y = Value, x = Category, fill = Species,)) +
  geom_col(width = 0.98) +
   scale_fill_manual(values = custom_colors) + 
  #geom_text(vjust = -0.5) +  # Aggiungi le etichette sopra le barre
  theme_minimal()  # Usa un tema semplice

ggsave(filename = paste0("../results/images/MainRNA/StackedBarplotCST.svg"), plot = p, width = 15, height = 6, device = svglite)


#### Heatmap ####

annotationcol <- data_long %>% group_by(Category) %>% filter(Value==max(Value)) 
annotationcol <- data.frame(row.names = annotationcol$Category, Dominance=annotationcol$Species)

cluster_col <- data.frame(row.names = names(clusters),Clusters=clusters)#,Clusters_scaled=clusters_scaled)
cluster_col$Clusters <- paste0("cl_",cluster_col$Clusters)

final_annotationcol <- merge(annotationcol,cluster_col,by=0)
rownames(final_annotationcol) <- final_annotationcol$Row.names
final_annotationcol$Row.names <- NULL
final_annotationcol<-arrange(final_annotationcol,Clusters)


cluster_colors <- list(Clusters = c("cl_1" = "#468B74" , "cl_2" ="#F58B1F", "cl_3" = "#92C73E","cl_4" =  "#EC1E24"), Dominance=  c("Lactobacillus crispatus" = "#F58B1F", "Lactobacillus gasseri" = "#EC1E24","Lactobacillus iners" = "#92C73E",  "Others" = "#468B74"  ,   "Lactobacillus jensenii" = "#35459B"))



p <- pheatmap(kdata_frac, 
         cluster_rows = T, 
         cluster_cols = F,
         annotation_colors  = cluster_colors,
         annotation_col = final_annotationcol,
         scale= "row",
         fontsize_row = 8, 
         fontsize_col = 8,
         clustering_method = "ward.D2",
         angle_col = 45,
         color = viridis(100),
         breaks= seq(-1.2,1.5,length.out=100)
         
)

ggsave(filename = paste0("../results/images/MainRNA/MainHeatmap.svg"), plot = p, width = 15, height = 6, device = svglite)

```

```{r Dams_cluster}

mann_whitney <- function(taxa,group) {
  group1<-rownames(subset(cluster_col,Clusters==group))
  group2<-rownames(subset(cluster_col,Clusters!=group))
  test <- wilcox.test(taxa[group1], taxa[group2])
  median_change <- median(taxa[group1]) - median(taxa[group2])
  return(data.frame(pvalue=test$p.value,logMedianChange=median_change))
}

dgeobj <- DGEList(counts=kdata_filt)
dgeobj <- calcNormFactors(dgeobj,method="TMM")
counts_norm <- cpm(dgeobj, normalized.lib.sizes=TRUE, log=TRUE)


DGE<-lapply(unique(cluster_col$Clusters), function(cluster) { 
           results<-apply(counts_norm, 1, function(taxa) mann_whitney(taxa,cluster))
           results<- do.call(rbind,results)
           results$padj<-p.adjust(results$pvalue, method = "BH") 
           return(results)
             })

names(DGE) <- unique(cluster_col$Clusters)
DGE_filt<- lapply(DGE,function(x) rownames(subset(x,padj<=0.1 & abs(logMedianChange)>=0.5)))
DGE_filt_list <- unique(do.call(c,DGE_filt)) 

pheatmap(counts_norm[DGE_filt_list,match(ordered_samples,colnames(counts_norm))], 
         cluster_rows = T, 
         cluster_cols = F,
         annotation_colors  = cluster_colors,
         annotation_col = final_annotationcol,
         scale= "row",
         fontsize_row = 10, 
         fontsize_col = 10,
         clustering_method = "ward.D2",
         # cutree_cols = 5,
         cutree_rows = 4,
         angle_col = 45,
         color = viridis(100),
         # breaks= seq(-1.2,1.5,length.out=100)
)

```


```{r}

bac2<-rowSums(apply(kdata_frac,2,FUN = function(x) x>=0.1))>=1
genus_frac_filt2<-kdata_frac[bac2,]
genus_frac_filt2["<10%",]<-1-colSums(genus_frac_filt2)
mypalette <- c("grey80","#f65356","#fb8066","#fea671","#fec979","#feea80","#d7e586","#a5de94","#5daad8","#8187c7","#c56bba","brown")

inerssamples<-rownames(annotationcol)[which(annotationcol$Dominance == "Lactobacillus iners")]
inersfrac<-genus_frac_filt2[,match(inerssamples,colnames(genus_frac_filt2))]
inersfrac$means<-rowMeans(inersfrac)
crispatussamples<-rownames(annotationcol)[which(annotationcol$Dominance == "Lactobacillus crispatus")]
crispatusfrac<-genus_frac_filt2[,match(crispatussamples,colnames(genus_frac_filt2))]
crispatusfrac$means<-rowMeans(crispatusfrac)
gasserisamples<-rownames(annotationcol)[which(annotationcol$Dominance == "Lactobacillus gasseri")]
gasserifrac<-genus_frac_filt2[,match(gasserisamples,colnames(genus_frac_filt2))]
gasserifrac$means<-rowMeans(gasserifrac)
otherssamples<-rownames(annotationcol)[which(annotationcol$Dominance == "Others")]
othersfrac<-genus_frac_filt2[,match(otherssamples,colnames(genus_frac_filt2))]
othersfrac$means<-rowMeans(othersfrac)

inplot<-ggplot(data=inersfrac,aes(x="",y=means,fill = rownames(inersfrac)))+
  geom_bar(stat="identity",width = 1)+
  scale_fill_manual(values = mypalette)+
  coord_polar("y",start=0)+
  xlab(label = "")+
  labs(fill="Species")+
  theme_minimal()

crisplot<-ggplot(data=crispatusfrac,aes(x="",y=means,fill = rownames(crispatusfrac)))+
  geom_bar(stat="identity",width = 1)+
  scale_fill_manual(values = mypalette)+
  coord_polar("y",start=0)+
    xlab(label = "")+
    labs(fill="Species")+
  theme_minimal()

gassplot<-ggplot(data=gasserifrac,aes(x="",y=means,fill = rownames(gasserifrac)))+
  geom_bar(stat="identity",width = 1)+
  scale_fill_manual(values = mypalette)+
  coord_polar("y",start=0)+
    labs(fill="Species")+
    xlab(label = "")+
  theme_minimal()


othersplot<-ggplot(data=othersfrac,aes(x="",y=means,fill = rownames(inersfrac)))+
  geom_bar(stat="identity",width = 1)+
  scale_fill_manual(values = mypalette)+
  coord_polar("y",start=0)+
    labs(fill="Species")+
    xlab(label = "")+
  theme_minimal()

p <- ggarrange(crisplot,inplot, gassplot, othersplot,
                    labels = c("CSTI", "CSTIII", "CSTII","CSTIV"),
                    ncol = 2, nrow = 2)
ggsave(filename = paste0("../results/images/MainRNA/supp/allCSTscake.svg"), plot = p, width = 15, height = 6, device = svglite)

```


```{r}
data_PCA = prcomp(t(kdata_frac), scale = T)
scores = data.frame(sample = rownames(data_PCA$x), PC1 = data_PCA$x[,1], PC2 = data_PCA$x[,2], PC3 = data_PCA$x[,3])
scores$sample = rownames(scores)
scores$status = sapply(strsplit(scores$sample,"_"),"[", 1)
scores$PatientID = sapply(strsplit(scores$sample,"_"),"[", 2)
scores = merge(scores,final_annotationcol,by = 0)
```

---

```{r echo=FALSE, message=FALSE, warning=FALSE}

NMDS <- vegan::metaMDS(
  t(kdata_frac), 
  distance = "bray", 
  trymax = 100,
  autotransform = TRUE,  
  k = 4                  
)



stress_value <- paste("Stress:", round(NMDS$stress, 3))
score <- data.frame(
  vegan::scores(NMDS)$site,
  sampleID = rownames(vegan::scores(NMDS)$site)
) %>%
  mutate(
    SampleGroup = sapply(strsplit(sampleID, "\\."), "[", 1)
  )
score <- merge(score,final_annotationcol,by = 0)
p <- ggplot(score, aes(x = NMDS1, y = NMDS2)) +
  geom_point(
    aes(fill = Dominance), 
    size = 6,
    alpha = 0.9,
    color = "grey40",      
    shape = 21,            
    stroke = 0.7           
  ) +
  scale_fill_manual(values = cluster_colors$Dominance,
                    name = "Community State Type", 
                    labels = c("CSTI", "CSTII", "CSTIII","CSTIV") 
                    ) +
  labs(
    title = "Non-Metric Multidimensional Scaling (NMDS)",
    subtitle = stress_value,
    x = "NMDS1",
    y = "NMDS2"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 18),
    plot.subtitle = element_text(hjust = 0.5, color = "gray40"),
    axis.title = element_text(face = "bold", color = "gray30"),
    panel.grid.major = element_line(color = "grey90"),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "white", color = NA)
  ) +
  coord_fixed() 
 ggsave(filename = paste0("../results/images/MainRNA/supp/NMDSCluster.svg"), plot = p, width = 8, height = 6, device = svglite)


```

```{r alphadiversity}

nreads_min<-min(colSums(kdata_filt))
nreads_max<-max(colSums(kdata_filt))
fold<-round(nreads_max/nreads_min,0)

kdata_subs<-rrarefy(t(kdata_filt),nreads_min)
alpha_subs<-diversity(kdata_subs)
alphasubs=data.frame(samples=names(alpha_subs),value=alpha_subs)
alphasubs$samples<-factor(alphasubs$samples,ordered_samples)
alphasubs<-merge(alphasubs,final_annotationcol,by=0) %>% tibble::column_to_rownames("Row.names")

alphasubs <- alphasubs %>%
  mutate(Dominance = case_when(
    Dominance == "Lactobacillus crispatus" ~ "CSTI",
    Dominance == "Lactobacillus iners" ~ "CSTIII",
    Dominance == "Lactobacillus gasseri" ~ "CSTII",
    Dominance == "Others" ~ "CSTIV",
  ))
my_comparisons <- list( c("CSTIV","CSTI"),c("CSTIV","CSTIII"),c("CSTIV","CSTII"),c("CSTIII","CSTI"),c("CSTII","CSTI"),c("CSTIII","CSTII"))

p <- ggplot(alphasubs,aes(x=Dominance,y=value,fill = Dominance))+
  geom_boxplot()+  
  scale_fill_manual(values = c("CSTIV" = "#468B74" , "CSTI" ="#F58B1F", "CSTIII" = "#92C73E","CSTII" =  "#EC1E24"))+
  stat_compare_means(comparisons=my_comparisons)+
  theme_bw()

ggsave(filename = paste0("../results/images/MainRNA/supp/Boxplotalpha.svg"), plot = p, width = 8, height = 6, device = svglite)


p <- ggplot(alphasubs, aes(x = samples, y = factor(1), size = value, colour = value)) +
  geom_point() +
  scale_size_continuous(range = c(5, 15)) +
  scale_color_gradient(low = "grey90", high = "#D94943") +  
  theme_bw() +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none"  
  )+
  coord_fixed(ratio = 2)
ggsave(filename = paste0("../results/images/MainRNA/alphascore.svg"), plot = p, width = 15, height = 6, device = svglite)


```



```{r}
genus_frac<-kdata_frac
genus_frac$genus<-sapply(strsplit(rownames(genus_frac)," "),"[",1) 
genus_frac<-genus_frac %>%
  group_by(genus) %>%
  summarise(across(everything(), sum, na.rm = TRUE)
  )%>% tibble::column_to_rownames("genus")

genus_frac$sum <- rowSums(genus_frac)

genus_frac<-arrange(genus_frac,desc(sum))
genus_frac$sum<-NULL

prc=0.05
bac<-rowSums(apply(genus_frac,2,FUN = function(x) x>= prc))>=1
genus_frac_filt<-genus_frac[bac,]


correlation<-cor(t(genus_frac_filt))
p <- pheatmap(correlation)
ggsave(filename = paste0("../results/images/MainRNA/supp/correlationgeneri.svg"), plot = p, width = 10, height = 6, device = svglite)

```

```{r}

mypalette<-c("#ac99ba","#54478c" ,"#2c699a", "#0db39e", "#83f377", "#b9e769", "#efea5a", "#f1c453", "#f29e4c","#f26e2c","#D94943","#a4161a","#61161a","#21161a")
genus_frac_filt$Genus <- rownames(genus_frac_filt)

data_long_gen <- genus_frac_filt %>%
  pivot_longer(
    cols = starts_with("H_"),   
    names_to = "Category",      
    values_to = "Value"         
  ) 


data_long_gen<-merge(data_long_gen,final_annotationcol,by.x="Category",by.y=0)
data_long_gen$Category<-factor(data_long_gen$Category,levels = ordered_samples)

p <- ggplot(data_long_gen, aes(y = Value, x = Category, fill = Genus)) +
  geom_col(width = 0.98) +
  scale_fill_manual(values = mypalette)+
  theme_minimal() 
ggsave(filename = "../results/images/MainRNA/supp/BarPlotGeneri.svg", plot = p, width = 8, height = 6,device = svglite)

data_long_gen<-subset(data_long_gen,Genus!="Lactobacillus")

p <- ggplot(data_long_gen, aes(x = Genus, y = Category, size = Value, fill = Genus)) +
  geom_point(alpha = 0.7, shape = 21) +
  ggtitle(label=paste0("BubblePlot ",prc*100,"%"))+
  scale_fill_manual(values = mypalette)+
  scale_size_continuous(range = c(0, 27)) + 
  theme_minimal()+ 
  theme(legend.position = "right",axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1)) 

ggsave(filename = "../results/images/MainRNA/BubblePlotGeneri.svg", plot = p, width = 8, height = 10,device = svglite)



my_comparisons <- list( c("Lactobacillus crispatus", "Lactobacillus iners"), c("Lactobacillus iners", "Lactobacillus gasseri"), c("Lactobacillus crispatus", "Others"),c("Lactobacillus gasseri", "Others"),c("Lactobacillus iners", "Others"),c("Lactobacillus crispatus", "Lactobacillus gasseri"))


data_long_gen$Cluster<-final_annotationcol[match(data_long_gen$Category,rownames(final_annotationcol)),]$Dominance

p=ggplot(data_long_gen,aes(x = Cluster,y=Value,fill = Cluster))+
  geom_boxplot()+
  geom_jitter(alpha=0.9)+
  facet_wrap(~Genus,scales="free")+
  stat_compare_means(comparisons = my_comparisons)+
  scale_fill_manual(values = cluster_colors$Dominance,
                    name = "Community State Types", 
                    labels = c("CSTI", "CSTII", "CSTIII","CSTIV") 
                    )+
   scale_x_discrete(labels = c("CSTI", "CSTII", "CSTIII", "CSTIV")) +
   labs(title = "Abundances of Microorganism in Clusters",
        x="",
        y="") +
  theme_minimal()
ggsave(filename = "../results/images/MainRNA/supp/AbundancesinClusters.svg", plot = p, width = 15, height = 15,device = svglite)
```
```{r}

association <- read.csv("../local/data/MicroPhenoDBAssociationScores.csv") %>% select(-Pmid, -Association_ID)
key_cols <- setdiff(names(association), "Score")


merged_dupl <- merge(kdata_frac, association, by.x = 0, by.y = "Microbe")

# Compute the mean of 'Score' while grouping by 'Row.names'
Scores <- merged_dupl %>%
    group_by(Row.names) %>%
    summarise(Score = mean(Score, na.rm = TRUE), .groups = "drop") %>%
    tibble::column_to_rownames("Row.names")

merged <- merge(kdata_frac,Scores,by=0)%>%tibble::column_to_rownames("Row.names")


diseasescore<-list()
for (names in setdiff(colnames(merged), c("Score","Genus"))) {

diseasescore[names]<-sum(merged[,names]*merged[,"Score"])  
  
}

disbiodb=data.frame(samples=names(unlist(diseasescore)),dysbio=unlist(diseasescore))
disbiodb$samples=factor(disbiodb$samples,ordered_samples)
disbiodb$dysbio<-disbiodb$dysbio

p <- ggplot(disbiodb, aes(x = samples, y = factor(1), size = dysbio, colour = dysbio)) +
  geom_point() +
  scale_size_continuous(range = c(5, 15)) +
  scale_color_gradient(low = "grey90", high = "#0070BB") +  # Intensity of color
  theme_bw() +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none"  # Hide the legend
  )+
  coord_fixed(ratio = 2)

ggsave(filename = paste0("../results/images/MainRNA/disbioscore.svg"), plot = p, width = 15, height = 6, device = svglite)
write.csv(merge(final_annotationcol,disbiodb,by=0) %>% tibble::column_to_rownames("Row.names"),"../results/cluster_col.csv")

```
```{r}
library(ggthemes)
x <- merge(disbiodb,alphasubs)


# Calculate the correlation coefficient
correlation <- cor(x$value, x$dysbio)

# Create the plot
plot <- ggplot(x, aes(x = value, y = dysbio)) +
  # Add points with a refined aesthetic
  geom_point(size = 3.5, alpha = 0.9, shape = 21, fill = "#34495E") +
  
  # Add a smooth regression line with confidence interval
  geom_smooth(method = "lm", se = TRUE, color = "#E74C3C", fill = "#FADBD8", linewidth = 1.5) +
  
  # Add dynamic annotation for correlation score
  annotate("text", x = max(x$value) * 0.8, y = max(x$dysbio) * 0.9,
           label = paste("Correlation: r =", round(correlation, 2)),
           color = "#34495E", size = 5, fontface = "italic") +
  
  # Add custom labels with refined typography
  labs(
    title = "Correlation AlphaDiversity and Dysbiosis",
    subtitle = "scatterplot and regression line",
    x = "Alpha Diversity",
    y = "Dysbiosis Score"
  ) +
  
  # Apply a sophisticated theme for professional presentation
  theme_bw(base_size = 16) +
  
  # Customize theme elements for visual hierarchy
  theme(
    panel.grid.major = element_line(color = "grey85"),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(color = "#34495E", size = 1),
    axis.title.x = element_text(size = 14, face = "bold", margin = margin(t = 10)),
    axis.title.y = element_text(size = 14, face = "bold", margin = margin(r = 10)),
    axis.text.x = element_text(size=12),
    axis.text.y=element_text(size=12),
    plot.title=element_text(size=20, face="bold", hjust=0.5, color="#2C3E50"),
    plot.subtitle=element_text(size=16, hjust=0.5, color="#7F8C8D"),
    legend.position="none"
  )

plot
ggsave(filename = "../results/images/MainRNA/supp/corralphadisbyo.svg", plot = plot, width = 8, height = 6,device = svglite)
```